/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HeadRouteImport } from './routes/head'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CitizenIndexRouteImport } from './routes/citizen.index'
import { Route as CitizenReportRouteImport } from './routes/citizen.report'
import { Route as CitizenIdRouteImport } from './routes/citizen.$id'

const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadRoute = HeadRouteImport.update({
  id: '/head',
  path: '/head',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIndexRoute = CitizenIndexRouteImport.update({
  id: '/citizen/',
  path: '/citizen/',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenReportRoute = CitizenReportRouteImport.update({
  id: '/citizen/report',
  path: '/citizen/report',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenIdRoute = CitizenIdRouteImport.update({
  id: '/citizen/$id',
  path: '/citizen/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/head': typeof HeadRoute
  '/login': typeof LoginRoute
  '/worker': typeof WorkerRoute
  '/citizen/$id': typeof CitizenIdRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/': typeof CitizenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/head': typeof HeadRoute
  '/login': typeof LoginRoute
  '/worker': typeof WorkerRoute
  '/citizen/$id': typeof CitizenIdRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen': typeof CitizenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/head': typeof HeadRoute
  '/login': typeof LoginRoute
  '/worker': typeof WorkerRoute
  '/citizen/$id': typeof CitizenIdRoute
  '/citizen/report': typeof CitizenReportRoute
  '/citizen/': typeof CitizenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/head'
    | '/login'
    | '/worker'
    | '/citizen/$id'
    | '/citizen/report'
    | '/citizen/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/head'
    | '/login'
    | '/worker'
    | '/citizen/$id'
    | '/citizen/report'
    | '/citizen'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/head'
    | '/login'
    | '/worker'
    | '/citizen/$id'
    | '/citizen/report'
    | '/citizen/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  HeadRoute: typeof HeadRoute
  LoginRoute: typeof LoginRoute
  WorkerRoute: typeof WorkerRoute
  CitizenIdRoute: typeof CitizenIdRoute
  CitizenReportRoute: typeof CitizenReportRoute
  CitizenIndexRoute: typeof CitizenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/head': {
      id: '/head'
      path: '/head'
      fullPath: '/head'
      preLoaderRoute: typeof HeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/': {
      id: '/citizen/'
      path: '/citizen'
      fullPath: '/citizen/'
      preLoaderRoute: typeof CitizenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/report': {
      id: '/citizen/report'
      path: '/citizen/report'
      fullPath: '/citizen/report'
      preLoaderRoute: typeof CitizenReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen/$id': {
      id: '/citizen/$id'
      path: '/citizen/$id'
      fullPath: '/citizen/$id'
      preLoaderRoute: typeof CitizenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  HeadRoute: HeadRoute,
  LoginRoute: LoginRoute,
  WorkerRoute: WorkerRoute,
  CitizenIdRoute: CitizenIdRoute,
  CitizenReportRoute: CitizenReportRoute,
  CitizenIndexRoute: CitizenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
